### ISSUE TITLE
Clarify licensee in LICENSE.txt

### ISSUE THREAD

**Issue by peanutfun** [mithun218/GiNaCDE#1]
### Description

The [`LICENSE.txt`](https://github.com/mithun218/GiNaCDE/blob/f332d194ec753ab2afa7e14c983e2d3f0699bfbf/LICENSE.txt) file lists the licensee "Barak Shoshany", although the author of this repository appears to be @mithun218 ("Mithun Bairagi" according to the JOSS submission). I guess this is a simple copy-paste error? Please clarify and update the license file accordingly.

### Related issues

openjournals/joss-reviews#3885

**Comment by mithun218** [comment]
You are right. It was a simple copy-paste error. The licensee will be Mithun Bairagi (the author of this repository). I have fixed this issue in [2594454](https://github.com/mithun218/GiNaCDE/commit/259445470b79bc4b65260b34a6c23c58088e1e42).

**Comment by peanutfun** [comment]
Thank you!
